### ISSUE TITLE
Realtime usage?

### ISSUE THREAD

**Issue by paulcanning** [DavidArayan/ezy-slice#1]
Can this be used in realtime?

If so, could you do an example scene of how to do so?

Thanks!

**Comment by DavidArayan** [comment]
Yes, This was designed first and foremost for real-time usage. The total time it would take for the algorithm to process really depends on the complexity of the mesh you are cutting.

This was done as a side project so its not super-optimized, but I think its good enough for very simple use cases. 

I'll throw together a real-time example scene in the coming days, I've been meaning to do a fun little project in VR anyway!

**Comment by paulcanning** [comment]
Cheers!

I figured out how to trigger it, but more examples would be nice :)

**Comment by PatriceKast** [comment]
Hi there

I was just trying to achive the same thing (to slice an object during runtime)
but it didn't work...

I didn't find a runtime demo of the slicer framework, so could you please upload one? Would help me a lot :)

Cheers

**Comment by DavidArayan** [comment]
I've just completed a full refactor of the code (now on master branch). I'll look into adding a very simple realtime slicing demo soon.

**Comment by PatriceKast** [comment]
@DavidArayan Thank you so much, this would help! :)

**Comment by ymrg3307** [comment]
@paulcanning @DavidArayan @PatriceKast  how did you achieve this? can you give me a step by step process

**Comment by RaidelRoss** [comment]
Does not work on mobile

**Comment by paulcanning** [comment]
I had it working on mobile no issue

**Comment by DavidArayan** [comment]
@RaidelRoss As per the issue [Android Crash](https://github.com/DavidArayan/EzySlice/issues/16) try to switch to the IL2CPP backend and try again. There seems to be some problems with Mono.
