### ISSUE TITLE
[Feature] - Submesh Material batching when slicing

### ISSUE THREAD

**Issue by DavidArayan** [DavidArayan/ezy-slice#10]
The Slicer relies on sub-meshing to store the polygon data for the cross section. When slicing an already sliced mesh, the framework will continue to add a sub-mesh which increases the array, increases the draw count and eventually leads to errors.

An enhanced mechanism will allow the slicer to reuse sub-meshes (similar to batching) if it detects that the desired Material is the same as from the original object. This will allow Meshes to be continually sliced, guaranteeing only 2 sub-meshes for cases where the Materials don't change.

This will be added as an enhancement over the existing API and will be performed behind the scenes automatically.

**Comment by PotatoBo** [comment]
There is also the case to consider where an object with two cut faces having different materials gets those cut faces sliced off, resulting in only a single cut face on the object which previously had 2, requiring shrinking the material array. Not sure if what you had in mind for implementing the batching would handle this case but it's just something to consider. Not a big deal if the batching only supports 2 materials properly for now (cut face and object). Looking forward to this batching feature!

**Comment by DavidArayan** [comment]
Greetings,

I've added submesh batching for the slicer as of commit fbb271fad6762b7a81c18f4bba19bdd59defbfca. The slicer will now use the submesh which shares the same material as the original object. This should help with the endless submesh additions especially with repeated slicing. Let me know if any problems come up! I will now close this issue.
