### ISSUE TITLE
Only creating necessary Hulls?

### ISSUE THREAD

**Issue by ymrg3307** [DavidArayan/ezy-slice#14]
I came into a doubt, Is it really necessary to create a hull when the plane is not cutting the game object,
What I am trying to say for example the cutting plane is entirely above the game object to be cut and is parallel to the game object, In this case, I am thinking the cutting is really not necessary because of there is no intersection between plane and game object but In your algorithm, the lower shell is being created automatically.The same goes for when the plane is entirely below and parallel to the game object.
Is there any case where you require this behaviour?
In both these cases, I think there is no need for cutting.It's just a doubt.

**Comment by DavidArayan** [comment]
Greetings,

Thank you for bringing this to my attention. And you are correct, this is not meant to happen. The slicer should just return a null array if no slicing occurred. I will investigate and apply a patch!

**Comment by DavidArayan** [comment]
Greetings,

This bug has been fixed as part of commit fbb271fad6762b7a81c18f4bba19bdd59defbfca. Please let me know if the problem persists. I will now close this issue.

**Comment by ymrg3307** [comment]
Its working fine now thanks for resolving it and on more help can you provide a list of api commands used in your framework.What I am asking like a reference for your framework(for eg., UNITY api reference)
you can make a slide or doc file and give a link for us
