### ISSUE TITLE
Possible to change plane to something else?

### ISSUE THREAD

**Issue by nemesiscy** [DavidArayan/ezy-slice#17]
Hello! I really love your EzySlice framework. Just wanna ask is it possible if I want to change 

FROM
"Cutting objects with plane." 
TO
"Cutting objects with uneven plane, for example, a wavy plane. Probably an object that have a mesh filter of a wavy plane. I'm trying to achieve a bite mark effect on food models."

Hope you understand my question. Thanks in advance!

**Comment by DavidArayan** [comment]
Greetings nemesiscy,

Unfortunately it's not currently possible to cut an object with an uneven plane. What you're looking for is some form of mesh segmentation which is generally offered in standalone tools such as Maya or Blender. Algorithms to do that generally require some kind of pre-processed version of a mesh which is expensive to compute and process, not really for real-time usage.

What you could do is pre-process your mesh in an external tool and do a simple switch at runtime via scripts. It's not ideal but would work. I think older versions of fruit ninja used that kind of technique.

Good luck!

**Comment by nemesiscy** [comment]
Okay. Thanks for your knowledge and reply!
