### ISSUE TITLE
A little help on Slicing an object.

### ISSUE THREAD

**Issue by ghost** [DavidArayan/ezy-slice#20]
Ill be honest, I have no idea how to use this.

I just want to slice an object when it gets in touch with another when collided. 

Example a sword through a branch of a tree.

I've messed around with the example scene but there seems to be a button to slice the things. Im not sure if Im looking at the right thing.

Anything would be helpful! thank you!

**Comment by DavidArayan** [comment]
Hello @xCured2,

The Example Scenes are just that, example code to show you how the slicer works. They are not part of the core framework.

When you import the Slicer framework, there are various extension methods which you need to use to cut objects. The one most suitable for you is the [gameObject.Slice(worldPosition, worldDirection)](https://github.com/DavidArayan/EzySlice#direct-instantiated-example). So you will need to do the following.

1. Detect a [Collision](https://unity3d.com/learn/tutorials/topics/physics/detecting-collisions-oncollisionenter) between the tree and the sword
2. Grab the tree GameObject, ensuring it has the MeshFilter with a mesh in it (describing the tree)
3. Grab the position and orientation of your sword and call tree.Slice(swordWorldPosition, swordWorldDirection).
4. Grab the sliced GameObject (if any) and do whatever you'd like to do. You may need to manually destroy your tree and re-instantiate the returned GameObject's.

All things given, the slice should be a single line of code.

Keep in mind that the Slice returns new objects which you will need to re-attach any scripts into (if you had any on the tree).

Hope that helps!

**Comment by ghost** [comment]
That indeed helped a lot! I was just unsure on how to exactly use this but that comment has it all figured out for me!

Thank you!

**Comment by superbuck** [comment]
Hi,

I've got a similar question: 
I want to slice an object in either the x axis or the y axis. (Worlddirection) 
For the Worldpoint I define a point on the object (chosen with a airtab on the object) 
If I do so, the object is always sliced with the same plane for different points on the object.
What am I doing wrong?

**Comment by DavidArayan** [comment]
@superbuck The Plane you use to slice also has a rotation defined, the point only defines the position, you also need to define the rotation. Rotation is arbitrary and will change the axis that the slice occurs, check some of the samples on how it's done, cheers!

**Comment by superbuck** [comment]
Why do I ned to define the rotation? 
Just that I get it right: with the Position one defines the a point on the cutting plane and with the Direction one defines the normal to the plane. With this a cutting plane should be created at the defined Position with alignment to the normal, is this right?

**Comment by DavidArayan** [comment]
Correct, The normal defines the facing direction of the plane, essentially it's rotation in 3D space. So just make sure the normal that you provide is actually a normalized vector.

**Comment by superbuck** [comment]
Thank you, that helped with that problem.
Another issue witht the Ezyslice Toolbox: 
When I cut my object, then at some places there are "holes", so no mesh is generated, where before was an mesh. Do you have any suggestion to solve this problem?

**Comment by DavidArayan** [comment]
Hello,

That sounds like a bug, if you could open a new bug report issue and post a screenshot of the problem occurring that would be fantastic! thank you.
