### ISSUE TITLE
Ezyslice crashes on IOS.

### ISSUE THREAD

**Issue by nemesiscy** [DavidArayan/ezy-slice#21]
The game crashes when slicing is attempted. Doesnt seem to be a RAM issue because i tested on IPhone XR, it crashes. But it doesnt crash on IPhone 5C. Do you have any idea on the possible issues of the crash?

From the XCode Debug Log, error EXC_BAD_ACCESS happens when i do the slicing.

I've tried unticking Auto Graphics API, removing Metal from the Graphics API but it's still not working currently.

**Comment by DavidArayan** [comment]
Hello,

Would you be able to provide a debug output of the crash?

**Comment by nemesiscy** [comment]
This is a build that includes Metal in the Graphics API. As attached is a .txt of the Debug Output. 
Im not seeing any errors on the debug output or im missing it. So, Ill post a screenshot of the EXC_BAD_ACCESS error too.

[DebugLog.txt](https://github.com/DavidArayan/EzySlice/files/2938892/DebugLog.txt)
![screen shot 2019-03-07 at 8 31 37 am](https://user-images.githubusercontent.com/30323195/53923625-f2e61780-40b3-11e9-985b-cf3b2f49b03c.png)

**Comment by nemesiscy** [comment]
This is a build without Metal in the Graphics API. I saw some solution saying to disable Metal so i tried it. But its not working but ill still post the debugs here.


[DebugLogWithoutMetal.txt](https://github.com/DavidArayan/EzySlice/files/2938917/DebugLogWithoutMetal.txt)
![screen shot 2019-03-07 at 8 45 48 am](https://user-images.githubusercontent.com/30323195/53924107-b6b3b680-40b5-11e9-991d-bca998f0a390.png)

**Comment by DavidArayan** [comment]
That's interesting. So it's crashing when either reading or assigning vertices from the object. When you run this code in the Unity Editor, you don't get any crashes?

**Comment by nemesiscy** [comment]
Unity Editor works fine, note that it only crashes in some IOS devices. 5C works fine, XR crashes, IPAD Mini 3 crashes.

**Comment by DavidArayan** [comment]
I tested the code on Iphone 7 and seems to be running fine. This looks like some kind of race-condition with the Mesh objects. Could you please check the following things.

1. The GameObject you are slicing is not destroyed before the slicer has an opportunity to run. This can occur if you're running the slicer in a coroutine and doing things with the GameObject elsewhere.
2. The GameObject you are slicing does not get destroyed in another thread while it's being sliced.
3. There is currently no support for multi-threaded slicing, just making sure you're not performing slice operations in a thread other than the main thread.
