### ISSUE TITLE
Incorrect plane slice with non uniform scale

### ISSUE THREAD

**Issue by BrahimHadriche** [DavidArayan/ezy-slice#23]
If the object is not scaled in a uniform way (e.g scaleX, scaleY, and scaleZ are different) then the slicing is not correct.

How to reproduce:

1. Open `SliceDebugScene` from https://github.com/DavidArayan/EzySlice-Example-Scenes
2. Change scale of `ObjectToSlice` in the editor from `(10, 10, 10)` to `(10, 50, 10)` for example
3. Set the `SlicerPlane` field and click `Cut Object`
4. Inspect the resulting objects (`Lower_Hull` and `Upper_Hull`)

**Comment by DavidArayan** [comment]
Thank you for the bug report, i've reproduced the error locally and will work on a fix.

**Comment by Wully616** [comment]
Any luck trying to resolve this?

**Comment by DavidArayan** [comment]
In order to solve this issue the cut will need to happen in world space. This means transforming all vertices into world space, performing the cut operation and transforming the resulting points back into object space. This results in a fairly heavy computation cost so instead of "fixing" the current method, i'd probably add in an option to slice non uniform scaled objects separately at the cost of additional computation/time.

My apologies for not communicating this sooner. At the moment i'm slowly investigating moving the slicer into Unity Job System that would allow slices to be performing drastically faster. The new redesign would allow me to fix lingering issues such as these much easier.

**Comment by RamonBeast** [comment]
Hello @DavidArayan is this still under work?
Thank you

**Comment by alexanderameye** [comment]
This is a pretty major issue.. Is there a simple workaround that does not involve rewriting code? Or is the only 'fix' to just use something like 'apply scale' in Blender/modeling program to make sure the imported object has a uniform scale.

**Comment by DavidArayan** [comment]
Hello @alexanderameye,

No need for a rewrite. The issue lays in transforming the cutting plane from world space to object space for the cut however i've recently discovered that direction vectors need to be transformed using the inverse transpose matrix (noob mistake, should have known better!). I'll attempt to test and push a fix for this today or early this week.

Cheers!

**Comment by alexanderameye** [comment]
Looking forward to it! And no hurry, I love the framework, thank you so much for sharing it. It's a valuable educational resource as well :)

**Comment by DavidArayan** [comment]
Hello,

As of the latest commit b98da2a this issue should be resolved and can finally be closed. I've modified the SlicerExtensions.cs code so the Plane direction vector is properly transformed into the object local space before slicing.

Unfortunately this also means that the old method of using [Transform.InverseTransformDirection](https://docs.unity3d.com/ScriptReference/Transform.InverseTransformDirection.html) or [Transform.InverseTransformVector](https://docs.unity3d.com/ScriptReference/Transform.InverseTransformVector.html) are incorrect. Unity should be using the Transpose Inverse Matrix to transform direction vectors for correct results. Maybe this is something that can be brought up with the Unity3D engineering team directly as a bug report. As a work around, i'm transposing and inverting the matrix manually for the correct results.

I will now close this issue. Thanks everyone!

Edit: See correct results after cutting a non-uniformly scaled object from following screenshot.

<img width="340" alt="Screen Shot 2021-02-02 at 5 11 28 pm" src="https://user-images.githubusercontent.com/7587896/106561511-eb1f9e00-657c-11eb-8bc6-ec5c78fb54d6.png">
