### ISSUE TITLE
Holes in mesh after cutting

### ISSUE THREAD

**Issue by superbuck** [DavidArayan/ezy-slice#24]
Hi, 
The problem I'm facing currently is: after I cut my object, some of the mesh is missing and there are some "holes" in the object. 
Here is the uncut object:
![uncutobject](https://user-images.githubusercontent.com/50164637/57916389-0de2be00-7893-11e9-850b-7a1c1a875685.PNG)
Here is the cut object:
![cutobject](https://user-images.githubusercontent.com/50164637/57916385-0c18fa80-7893-11e9-99be-7410d393cc80.PNG)
Here is another example: 
![cutobject2](https://user-images.githubusercontent.com/50164637/57917140-58b10580-7894-11e9-8d29-5e947a8c0bd6.PNG)

**Comment by DavidArayan** [comment]
Hi superbuck,

The object you're trying to cut, is it convex? From the screenshots you provided it doesn't look like a convex object. Just need to keep in mind that concave slicing is not yet supported because triangulating the cross section requires a more complicated (and slower) algorithm.

**Comment by superbuck** [comment]
Hi David,

How do I know, if my object is convex? Could it be set manually to a convex object?
The problem only occurs in the upper part of my object, the other part is cut with nice meshes. 
I do not see, why the meshes of the upper part are disappearing... 
Thank you for your help.
