### ISSUE TITLE
Bug: wrong slice direction when object we want to cut has different localscale on axis

### ISSUE THREAD

**Issue by hoangpl** [DavidArayan/ezy-slice#28]
Hi,
i want to report a bug : if object we want to cut has different localscale on axis ,
for example localscale = new Vector3 ( 0.5 , 1 , 3) ; (0 .5 # 3 # 1) , the sliced face is on wrong direction.
If localscale of them is equal , everything works fine
Thanks

**Comment by DavidArayan** [comment]
Hello hoangpl,

Thank you for the bug report! This bug has already been reported and is being tracked in the following [Issue](https://github.com/DavidArayan/ezy-slice/issues/23). I'll close this one to avoid duplicates, cheers!
