### ISSUE TITLE
The name 'Normal' does not exist in the current context

### ISSUE THREAD

**Issue by pxhan87** [DavidArayan/ezy-slice#33]
Plane.cs(61,35): error CS0103: The name 'Normal' does not exist in the current context

`public Plane(Vector3 a, Vector3 b, Vector3 c)
        {
            m_normal = Vector3.Normalize(Vector3.Cross(b - a, c - a));
            m_dist = -Vector3.Dot(Normal, a);

            // this is for editor debugging only!
#if UNITY_EDITOR
            trans_ref = null;
#endif
        }`

**Comment by DavidArayan** [comment]
Hello,

Thank you for bringing this to my attention. The issue has now been fixed.
