### ISSUE TITLE
Script Doesn't Link To Editor

### ISSUE THREAD

**Issue by TheCaptainMoo** [DavidArayan/ezy-slice#34]
Hello, It says here that the script's name doesn't match the file or there are no scripts in the file, what is the problem?

**Comment by DavidArayan** [comment]
Hi, could you provide some further details? cloning the repository on my end does not cause any issues. Make sure you're using the latest version of Unity3D.

**Comment by TheCaptainMoo** [comment]
Yeah, sorry that was the problem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
