### ISSUE TITLE
When cutting a complex mesh, the face does not respect the geometry

### ISSUE THREAD

**Issue by pruebasssaa** [DavidArayan/ezy-slice#38]
The intersection fill works well, although it does have problems when manipulating the mesh, since the fill does not respect the geometry: (I'm trying to deform the mesh, but the face doesn't fill well)
![error2](https://user-images.githubusercontent.com/52097934/83079088-6bd2e580-a051-11ea-8b3e-b884fb10e9a3.png)
Do you have any recommendations? Is there an easy way to get the vertices of the intersection so that I can fill it using my own code? Thank you

**Comment by DavidArayan** [comment]
Hi @pruebasssaa,

The slicer only fills the gaps correctly for convex objects. Concave object slicing is much more complicated. You'd need to look into the Intersection and Triangulation algorithms and develop your own solution.
