### ISSUE TITLE
Get the intersection points

### ISSUE THREAD

**Issue by pruebasssaa** [DavidArayan/ezy-slice#39]
First of all, I appreciate your quick help.

As you recommended, I am going to use my own algorithm to fill concave intersections, although I have problems obtaining the intersection points after the cut.

How can I do this? I can't find a way to do it

Thank you!

**Comment by DavidArayan** [comment]
Hi,

Have a look at the code in [Slicer.cs L478](https://github.com/DavidArayan/ezy-slice/blob/b93d68c24371a1fc7c7f0c3b70bd85ac28d950b0/EzySlice/Slicer.cs#L478) that uses MonotoneChain algorithm for the cross section triangulation. What you'd need to do is create your own triangulator and swap out MonotoneChain for your own version.

```List<Vector3> intPoints``` is the list of all intersection points when the cut occurs. At this point the Slicer has already created the other triangles and all you'd need to do is triangulate/create the surface from those points. You might need to consider sending more data through to that function to help with the triangulation.

Solving the triangulation for Concave cuts and all the edge cases (such as cuts with holes in them, cuts that create multiple separate objects etc..) is not a trivial problem to solve and I wish you all the best! If you manage to solve it, i'd love a pull request.

**Comment by pruebasssaa** [comment]
Sure! I will try, thanks, I can already work with the intersection points👍👍
