### ISSUE TITLE
[FEATURE] - Generate proper Normals and Tangents from the original mesh

### ISSUE THREAD

**Issue by DavidArayan** [DavidArayan/ezy-slice#4]
A recent feature request to generate normals and tangents from the original mesh which is being sliced. From observation it seems the final cut meshes do not render properly, this is due to using Mesh.RegenerateNormals() which is too generic.

- Look into using normals and tangents from the original mesh to ensure the cut mesh renders properly
- Ensure the generated normals and tangents work properly with the generated cross section

**Comment by PotatoBo** [comment]
This would be very useful. Currently when you slice a mesh it loses all the vertex normal data which gives it a faceted look. It makes it pretty jarring when you slice a mesh with carefully crafted smooth groups and it becomes faceted.

**Comment by DavidArayan** [comment]
Greetings,

Latest changes to commit 1b5ff4985bfd9153e5ab874a627e8e0c07ad1136 has added Normal and Tangent interpolation via Barycentric coordinates.

Slicing Meshes will now look at all UV, Normal and Tangent spaces for the Mesh. Please let me know if any bugs arise. I will close this feature.

**Comment by PotatoBo** [comment]
I found a small problem. If you try and cut the mesh and only a lower hull is generated due to the mesh being completely on the backside of the plane, it throws an out of range error due to SlicedSubmesh.hasUV trying to access upperHull[0].hasUV on an empty list. Other than that it seems to work very well!

**Comment by DavidArayan** [comment]
Greetings, 

Thank you for the bug report. I've fixed the problem in commit a00983bd49e396bd9b8a6d2383a6a9ab6bdd1dbe. I really need to setup some more testing scripts to catch all these cases!

**Comment by PotatoBo** [comment]
I believe I've found another small problem. If you apply a material with a normal map to a cut face it goes completely black. I think the tangents on the cut face are not set.

**Comment by DavidArayan** [comment]
Thank you for letting me know, I'll take a look shortly.

**Comment by DavidArayan** [comment]
Greetings,

Thank you for your patience. This should be fixed as of commit 45c8363e4c38a0efdb19567c5fbc0fc984ed4477.
