### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by chipohameja** [DavidArayan/ezy-slice#40]
This is not actually an issue with code or something, just with the documentation. I don't know how to, or how a game object is sliced. I've written all the codes here, but nothing is being sliced. How exactly does this work, what methods do I need to call inorder to slice something and how do I go about it???

Please help me 🙏🙏🙏🙏

**Comment by DavidArayan** [comment]
Hello,

Have you had a look at the number of uses and examples in [https://github.com/DavidArayan/ezyslice-example-scenes](https://github.com/DavidArayan/ezyslice-example-scenes)?

**Comment by chipohameja** [comment]
Yes I've seen the examples. I could barely understand some things due to
the complexity of the code. Regardless, I know the codes in the examples
can be written in a simpler way.
I intend to do a video tutorial once I get the concept because there are
some others out there that may be in my shoes

**Comment by DavidArayan** [comment]
The only function you need to call is GameObject.SliceInstantiate() referenced in [SlicerExtensions.cs L39](https://github.com/DavidArayan/ezy-slice/blob/b93d68c24371a1fc7c7f0c3b70bd85ac28d950b0/EzySlice/SlicerExtensions.cs#L39).

```c#
GameObject[] objects = gameObject.SliceInstantiate(myPlane);
```

or

```c#
Vector3 myKnifePosition = new Vector3(...);

// this needs to be normalised
Vector3 myKnifeDirection = new Vector3(...);

GameObject[] objects = gameObject.SliceInstantiate(myKnifePosition, myKnifeDirection);
```

**Comment by chipohameja** [comment]
Thanks, I finally get it
