### ISSUE TITLE
Doesn't work for more complex objects

### ISSUE THREAD

**Issue by sebastian-ruiz** [DavidArayan/ezy-slice#41]
I tested the demo project and it works for the cube in the demo project. However it doesn't work with my object.

I have a 3d model of a piece of toast, and I am trying to slice the toast. The lower_hull and upper_hull that are created from the slice are not what they should be. I have attached a screenshot here: 

<img width="1350" alt="Screenshot 2021-02-08 at 12 13 28" src="https://user-images.githubusercontent.com/2012398/107212396-31ef1700-6a07-11eb-9f90-5e5251661e44.png">

I have uploaded the 3d model here:

[toast.zip](https://github.com/DavidArayan/ezy-slice/files/5943459/toast.zip)

Thank you for your help!

**Comment by OzKitsune** [comment]
I also can't cut complex objects. Probably there is an overflow somewhere or something.

The toast is also not cut
![image](https://user-images.githubusercontent.com/54425262/107320630-d1d2a080-6aec-11eb-9333-7fc7a39c3e7e.png)

**Comment by DavidArayan** [comment]
I've just taken a look at this and its weird. Whatever is issue it seems to be a problem during the hull-generator phase where the vertices and indices of the re-constructed objects are all messed up. I'll keep looking to see if there is something i've missed... there might be some assumptions during the re-construction phase that i've forgotten about.

Also keep in mind that the slicer only works for Convex 3D Objects, the Toast is technically concave so even if the slice went through, you'd get artefacts around the cross section. You also might want to optimise that Toast, this is an O(n*log(n)) algorithm so it'll be quite slow for a 500k poly model.

**Comment by OzKitsune** [comment]
I solved the problem! It was indexFormat (by default 16 bit) which is not enough for large polygon models. I added for myself to Slicer.cs after 
`298 Mesh newMesh = new Mesh();`
next code:
`newMesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;`

Perhaps somewhere need to add a check for the number of vertices to select the index format.

P.S. Toast was sliced.
![image](https://user-images.githubusercontent.com/54425262/107839459-c38bc980-6df7-11eb-9b38-f9d85c952197.png)

**Comment by DavidArayan** [comment]
Great fix @OzKitsune ! I didn't realise that Unity uses 16 bit indices by default and thought its all 32 bit. 32 bit would double the storage requirement per index but I don't think thats a huge concern for modern hardware including mobile.

I'm happy to accept this fix as a pull request if you'd like to submit one?

**Comment by OzKitsune** [comment]
@DavidArayan sure, created a request.

**Comment by DavidArayan** [comment]
@OzKitsune Thank you for the pull request. It has been merged with master branch. Cheers!
