### ISSUE TITLE
[bug]Cut a hollow object in the middle. The object after cutting is incorrect

### ISSUE THREAD

**Issue by shoukailiang** [DavidArayan/ezy-slice#48]
For example, cutting the objects below
![image](https://user-images.githubusercontent.com/24668909/209566551-5b5938c2-f823-4b00-89e2-93447391b365.png)
![image](https://user-images.githubusercontent.com/24668909/209566570-e8108a1e-393c-4980-9bdf-b1352849dc4c.png)

The result is：
![image](https://user-images.githubusercontent.com/24668909/209566713-1b460944-e940-4767-9e1a-46ca8e6fbe62.png)
![image](https://user-images.githubusercontent.com/24668909/209566724-29bbe569-a981-482d-a59a-a42103f59315.png)
![image](https://user-images.githubusercontent.com/24668909/209566744-fa67d9af-d0f2-429e-af4b-250634c8b2eb.png)

**Comment by DavidArayan** [comment]
Not a bug, its a limitation. See Readme.

<img width="500" alt="Screenshot 2022-12-27 at 11 34 40 am" src="https://user-images.githubusercontent.com/7587896/209590673-5932e9f9-a201-4874-bc4b-089bfb40b82a.png">
