### ISSUE TITLE
[FEATURE] - Add an optional multi-threading API

### ISSUE THREAD

**Issue by DavidArayan** [DavidArayan/ezy-slice#5]
Adding an optional multi-threaded mode will allow for faster slicing and parallel slicing in real-time. This may take some time since I'll need to do some benchmarking against multiple slices, small/large object slicing etc..

- The multi-threaded API should be easy to use (prefer to have a single function call with a callback if possible). The main application should NOT care about the internal workings.
- Investigate into slicing large/complex objects simultaneously. Benchmark against single threaded slicing.
- Investigate into slicing small objects simultaneously. Benchmark against single threaded slicing.
- Look into using Thread pools to conserve performance for multiple slice jobs.
- Look into offloading Plane->Triangle slicing as a separate threaded job into a queue (instead of entire slicing jobs), what the performance implications are and if it's worth doing.
- Look into benchmarking memory usage and come up with a guideline on when to use/not use the threaded api.

**Comment by DavidArayan** [comment]
For those interested, there is now an experimental [feature/threading](https://github.com/DavidArayan/EzySlice/tree/feature/threading) branch in [EzySlice](https://github.com/DavidArayan/EzySlice/tree/feature/threading) projects and [EzySlice-Example-Scenes](https://github.com/DavidArayan/EzySlice-Example-Scenes/tree/feature/threaded) projects. The API is highly experimental and nowhere near complete, however the main Threading module is complete. I just need to make a decision on the new interface structure which will be needed to get the full benefits of multi-threaded slices. 

Once the new interfaces are complete, I'll merge the additions into master branch. Threading is likely to still remain as an optional interface alongside the single-threaded approach.

**Comment by Karol-G** [comment]
Hi,
in my application I want to slice multiple objects in parallel, so this sounds really interesting for me.
Is this branch still active?
Will you be able to do something like this then?
 Parallel.ForEach(gameObjectList.Cast<GameObject>(), gameObject => {Slicer.SliceThreaded(gameObject , cuttingPlane);});

**Comment by DavidArayan** [comment]
Greetings CookingCookie,

Yes indeed. You can find the threading branch @ [Threading Branch](https://github.com/DavidArayan/EzySlice/tree/feature/threading). Keep in mind that it is an experimental branch with experimental code and does not contain some of the recent changes in master branch. 

I'm currently waiting for the release of the Unity 2018 Job System to see if it's better to leverage Unity's built-in threading API's rather than rolling my own. There are also some complexities around working with the Mesh structure which (as far as I know) can only be created and modified in the main thread.

The idea of the threading addition is of course to allow cutting multiple objects (and multiple submeshes in a single object) in separate threads. I'm still exploring on whats the best method for doing so without degrading performance and making the garbage collector super angry. I'm not happy just slapping API's in a thread and calling it a day.

You are more than welcome exploring the threading branch and providing suggestions, even if they are simple high-level API suggestions (such as, how you'd like to use the API). This will give me ideas on how best to approach the actual implementation.

**Comment by DavidArayan** [comment]
I'm closing this feature request as the idea behind it is redundant. Ideally the slicer framework can move into the Unity3D DOTS system where triangles can be sliced in parallel. This would make for some very performant slices.
