### ISSUE TITLE
Unexpected hole patching after slice

### ISSUE THREAD

**Issue by yuhe0925** [DavidArayan/ezy-slice#50]
Here is a custom model that i used in the example SliceDebugScreen, after cutting, the part results as in the image :

![MicrosoftTeams-image (1)](https://github.com/DavidArayan/ezy-slice/assets/8944414/40538b5e-e110-4109-8422-e95d353afdcc)
![MicrosoftTeams-image](https://github.com/DavidArayan/ezy-slice/assets/8944414/37d4c1c2-5fe9-49f7-84f6-be905131564d)

it looks like that something went wrong after patching the hole after cutting, any advise how to solve this?

**Comment by DavidArayan** [comment]
Ezy-Slice solution only works with Convex 3D objects, I haven't really found a generalised triangulation solution that works with Concave 3D objects. Admittedly it's been a long time since I re-visited the problem.
