### ISSUE TITLE
Array Index Is Out Of Range

### ISSUE THREAD

**Issue by PotatoBo** [DavidArayan/ezy-slice#6]
Hi, I'm using Unity 5.4.5 and on some meshes I get "Array Index Is Out Of Range" on Slicer.cs Line 123 

`Triangle newTri = new Triangle(ve[i0], ve[i1], ve[i2], uv[i0], uv[i1], uv[i2]);` 

The meshes are simple shapes exported from blender as .obj (cube, icosphere).
Curiously, the default unity cube mesh works, but not one exported straight from blender. It appears the triangles are in a different configuration that's causing some bug (I think).

On the meshes that do work, when I call SliceInstantiate() the upper and lower hulls have no end caps on the cut face.

**Comment by DavidArayan** [comment]
Greetings,

Would you be able to provide one of your meshes which causes the out of bounds index error? Would help me replicate the issue! Thank you.

**Comment by PotatoBo** [comment]
Sure,

[CUBE.zip](https://github.com/DavidArayan/EzySlice/files/1701420/CUBE.zip)

**Comment by DavidArayan** [comment]
Greetings,

The issue was that your imported Mesh did not have any texture UV's added. I had not considered that case. I just did a commit 689483b0c2b6827680fa022cea031a15c630f33d which will not take UV's into account if the UV data is malformed.

You should now be able to slice your cube!

**Comment by PotatoBo** [comment]
Cool, thank you!

Regarding the caps for the cut face, do they work currently? When I call SliceInstantiate() the upper and lower hulls have no caps on the cut face.

**Comment by DavidArayan** [comment]
Greetings,

Seems I had forgotten to update the SliceInstantiate() functionality when I made the changes to the SubMesh Slicing. Apologies for that, I don't often use that function when testing!

I've updated the code in commit 44f2be234f66b5203d2abe881ccad50ab2991ad8 which makes sure the SliceInstantiate() is using the new API. I've tested and the example cube is slicing properly.
