### ISSUE TITLE
[Feature] World Space Slicing

### ISSUE THREAD

**Issue by PotatoBo** [DavidArayan/ezy-slice#9]
Currently, the plane you define for SliceInstantiate() cuts the mesh according to the object's local coordinate space. For example, when the object's coordinate space is aligned with world space any planes you define cut it as expected, but if the object rotates or moves, an xy plane will always cut the object along the object's local xy plane. I think it would be nice to have a parameter on SliceInstantiate() to signify if the plane should be treated as local or world space, so you can define a a world space xy plane, let's say, and just slice everything according to that properly, regardless of rotation and position.

**Comment by DavidArayan** [comment]
Greetings PotatoBo,

Thank you for the Request. This is currently achieved by bringing the current plane into the coordinate system of the object you wish to cut. I've provided an example @ [PlaneUsageExample.cs](https://github.com/DavidArayan/EzySlice-Example-Scenes/blob/master/EzySlice-Examples/Assets/Examples/Scripts/PlaneUsageExample.cs). Have a look at the ComputePlaneAgainst() function to see how this is done.

Though I agree that having an option in the Slicer would also be useful. I'll keep this request open so I can add a simple cutting option as part of the Slicer.

**Comment by DavidArayan** [comment]
Greetings,

As of commit fbb271fad6762b7a81c18f4bba19bdd59defbfca there is a new API which allows providing the plane position and direction in world space coordinates, which allows full world-space slicing. Let me know if any issues come up. I will close this issue.
